llm:
  api_type: "openrouter"
  model: "deepseek/deepseek-chat-v3-0324:free"
  base_url: "https://openrouter.ai/api/v1"
  api_key: "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"

models:
  "groq-llama3-70b":
    api_type: "openai"
    base_url: "https://api.groq.com/openai/v1"
    api_key: "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"
    model: "meta-llama/llama-4-scout-17b-16e-instruct"

terminal:
   executable: "C:\\projetosGFT\\MetaGPT\\bash_wrapper.bat"