# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "openrouter"
  model: "deepseek/deepseek-chat-v3-0324:free"
  base_url: "https://openrouter.ai/api/v1"
  api_key: "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"
